name: user_list
description: Flutter mobile App which present and edit User-List connected with database.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  users_api:
    path: packages/users_api
  users_repository:
    path: packages/users_repository

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0

flutter:

  uses-material-design: true
